name: Publish SDK

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write

jobs:
  publish-npm:
    if: contains(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org/'

      - name: Get version from package.json
        id: pkg
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install deps (also runs postinstall)
        run: npm install -g npm@latest

      - name: Publish to npm
        run: npm publish --access public

      - name: Create Git tag
        run: |
          git tag v${{ steps.pkg.outputs.version }}
          git push origin v${{ steps.pkg.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.pkg.outputs.version }}
          generate_release_notes: true
